version: 2.1
orbs:
  android: circleci/android@2.3.0

jobs:
  build:
    docker:
      - image: cimg/android:2023.09
    steps:
      - checkout
      - restore_cache:
          key: android-orb-v1-
      - run:
          name: Chmod permissions
          command: sudo chmod +x ./gradlew
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          key: 'android-orb-v1-{{ epoch }}'
          paths:
            - ~/.android/build-cache
            - ~/.android/cache
      - run:
          name: Run Build
          command: ./gradlew build
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - store_artifacts:
          path: app/build/outputs/apk/debug/
          destination: artifact-file

  test:
    override:
      # start the emulator
      - emulator -avd circleci-android31 -no-audio -no-window:
          background: true
          parallel: true
      # wait for it to have booted
      - circle-android wait-for-boot
      # unlock the emulator screen
      - sleep 30
      - adb shell input keyevent 82
      # run tests  against the emulator.
      - ./gradlew connectedAndroidTest -PdisablePreDex
      # copy the build outputs to artifacts
      - cp -r app/build/outputs $CIRCLE_ARTIFACTS
      # copy the test results to the test results directory.
      - cp -r app/build/outputs/androidTest-results/* $CIRCLE_TEST_REPORTS


  publish-github-release:
    docker:
      - image: cimg/android:2023.09
    steps:
      - checkout
      - restore_cache:
          key: android-orb-v1-
      - run:
          name: Chmod permissions
          command: sudo chmod +x ./gradlew
      - run:
          name: "Publish Release on GitHub"
          command: |
            VERSION="1.1"
            TAG_NAME="v${VERSION}"
            RELEASE_NAME="Release ${VERSION}"

            curl -X POST "https://api.github.com/repos/febri009/PadiCare/releases" \
              -H "Authorization: Bearer ${GH_TOKEN}" \
              -H "Content-Type: application/json" \
              -d '{
                "tag_name": "'"${TAG_NAME}"'",
                "name": "'"${RELEASE_NAME}"'",
                "body": "Release '"${VERSION}"'",
                "draft": false,
                "prerelease": false
              }'

workflows:
  version: 2
  workflow:
    jobs:
      - test