version: 2.1
orbs:
  android: circleci/android@2.3.0

jobs:
  build:
    docker:
      - image: cimg/android:2023.09
    steps:
      - checkout
      - restore_cache:
          key: android-orb-v1-
      - run:
          name: Chmod permissions
          command: sudo chmod +x ./gradlew
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          key: 'android-orb-v1-{{ epoch }}'
          paths:
            - ~/.android/build-cache
            - ~/.android/cache
      - run:
          name: Run Build
          command: ./gradlew build
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - store_artifacts:
          path: app/build/outputs/apk/debug/
          destination: artifact-file

  test:
    docker:
      - image: cimg/android:2023.09
    steps:
      - checkout
      - restore_cache:
          key: android-orb-v1-
      - run:
          name: Chmod permissions
          command: sudo chmod +x ./gradlew
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          key: 'android-orb-v1-{{ epoch }}'
          paths:
            - ~/.android/build-cache
            - ~/.android/cache
      - run:
          name: Run Tests
          command: ./gradlew lint test
      - store_test_results:
          path: app/build/test-results

  release:
    docker:
      - image: cimg/android:2023.09
    steps:
      - checkout
      - restore_cache:
          key: android-orb-v1-
      - run:
          name: Chmod permissions
          command: sudo chmod +x ./gradlew
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          key: 'android-orb-v1-{{ epoch }}'
          paths:
            - ~/.android/build-cache
            - ~/.android/cache
      - run:
          name: Build Release
          command: ./gradlew assembleRelease
      - persist_to_workspace:
          root: .
          paths:
            - app/build/outputs/apk/release/
      - deploy:
          name: Deploy to Kubernetes
          command: kubectl apply -f kubernetes/deployment.yaml

workflows:
  workflow:
    jobs:
      - build
      - test:
          requires:
            - build
      - release:
          requires:
            - test

