version: 2.1
orbs:
  android: circleci/android@2.3.0

jobs:
  build:
    docker:
      - image: cimg/android:2023.09
    steps:
      - checkout
      - restore_cache:
          key: android-orb-v1-
      - run:
          name: Chmod permissions
          command: sudo chmod +x ./gradlew
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          key: 'android-orb-v1-{{ epoch }}'
          paths:
            - ~/.android/build-cache
            - ~/.android/cache
      - run:
          name: Run Build
          command: ./gradlew build
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - store_artifacts:
          path: app/build/outputs/apk/debug/
          destination: artifact-file

  test:
    docker:
      - image: circleci/android:api-26-alpha
    steps:
      - run:
          name: Accept licenses
          command: yes | sdkmanager --licenses || true
      - run:
          name: List available system images
          command: sdkmanager --list
      - run:
          name: Setup emulator
          command: echo "no" | avdmanager create avd -n test -k "system-images;android-22;default;armeabi-v7a"
      - run:
          name: Launch emulator
          command: export LD_LIBRARY_PATH=${ANDROID_HOME}/emulator/lib64:${ANDROID_HOME}/emulator/lib64/qt/lib && emulator64-arm -avd test -noaudio -no-boot-anim -no-window -accel on
          background: true
      - run:
          name: Run Tests
          command: ./gradlew :demo:connectedAndroidTest

  publish-github-release:
    docker:
      - image: cimg/android:2023.09
    steps:
      - checkout
      - restore_cache:
          key: android-orb-v1-
      - run:
          name: Chmod permissions
          command: sudo chmod +x ./gradlew
      - run:
          name: "Publish Release on GitHub"
          command: |
            VERSION="1.1"
            TAG_NAME="v${VERSION}"
            RELEASE_NAME="Release ${VERSION}"

            curl -X POST "https://api.github.com/repos/febri009/PadiCare/releases" \
              -H "Authorization: Bearer ${GH_TOKEN}" \
              -H "Content-Type: application/json" \
              -d '{
                "tag_name": "'"${TAG_NAME}"'",
                "name": "'"${RELEASE_NAME}"'",
                "body": "Release '"${VERSION}"'",
                "draft": false,
                "prerelease": false
              }'

workflows:
  version: 2
  workflow:
    jobs:
      - test