version: 2.1
orbs:
  android: circleci/android@2.3.0

jobs:
  build:
    docker:
      - image: cimg/android:2023.09
    steps:
      - checkout
      - restore_cache:
          key: android-orb-v1-
      - run:
          name: Chmod permissions
          command: sudo chmod +x ./gradlew
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          key: 'android-orb-v1-{{ epoch }}'
          paths:
            - ~/.android/build-cache
            - ~/.android/cache
      - run:
          name: Run Build
          command: ./gradlew build
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - store_artifacts:
          path: app/build/outputs/apk/debug/
          destination: artifact-file

  test:
    docker:
      - image: cimg/android:2023.09

    working_directory: ~/app

    steps:
      - checkout

      # Start the emulator
      - run:
          name: Start Emulator
          command: |
            emulator -avd circleci-android31 -no-audio -no-window:
              background: true
              parallel: true

      # Wait for the emulator to boot
      - run:
          name: Wait for Emulator
          command: |
            circle-android wait-for-boot
            sleep 30
            adb shell input keyevent 82

      # Run tests against the emulator
      - run:
          name: Run Tests
          command: ./gradlew connectedAndroidTest -PdisablePreDex

      # Copy build outputs to artifacts
      - run:
          name: Copy Build Outputs
          command: cp -r app/build/outputs $CIRCLE_ARTIFACTS

      # Copy test results to the test results directory
      - run:
          name: Copy Test Results
          command: cp -r app/build/outputs/androidTest-results/* $CIRCLE_TEST_REPORTS


  publish-github-release:
    docker:
      - image: cimg/android:2023.09
    steps:
      - checkout
      - restore_cache:
          key: android-orb-v1-
      - run:
          name: Chmod permissions
          command: sudo chmod +x ./gradlew
      - run:
          name: "Publish Release on GitHub"
          command: |
            VERSION="1.1"
            TAG_NAME="v${VERSION}"
            RELEASE_NAME="Release ${VERSION}"

            curl -X POST "https://api.github.com/repos/febri009/PadiCare/releases" \
              -H "Authorization: Bearer ${GH_TOKEN}" \
              -H "Content-Type: application/json" \
              -d '{
                "tag_name": "'"${TAG_NAME}"'",
                "name": "'"${RELEASE_NAME}"'",
                "body": "Release '"${VERSION}"'",
                "draft": false,
                "prerelease": false
              }'

workflows:
  version: 2
  workflow:
    jobs:
      - test