apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    circleci.com/project-id: ee246bd1-f0e8-4d22-b1b6-2d8ed533ae70
  labels:
    app: padicare
    version: 1.0.0
  name: padicare-deployment
  namespace: default
spec:
  selector:
    matchLabels:
      app: padicare
  template:
    metadata:
      labels:
        app: padicare
        version: 1.0.0
    spec:
      containers:
        - name: padicare-container
          image: cimg/android:2023.09
      imagePullSecrets:
        -name: padicare-registry


