apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: padicare
    version: 1.0.0
  name: padicare-deployment
  namespace: default
spec:
  selector:
    matchLabels:
      app: padicare
  template:
    metadata:
      labels:
        app: padicare
        version: 1.0.0
    spec:
      containers:
        - name: padicare-container
          image: docker.io/febri009/padicare:latest


